ALTER FUNCTION  FN_OBTENER_CONVENIO_LIQUIDACION()
 RETURNS 
 @TABLE TABLE
 (
 CTG_D INT,
 DTG_D VARCHAR(255),
 COPERACION INT,
 DOPERACION VARCHAR(255)
 )
 AS
 BEGIN
INSERT INTO @TABLE
SELECT CTG_D,DTG_D,TOP1.CTIPO_OPERACION, TOP1.DOPERACION FROM (
select 
top 100
CTG_D,DTG_D, (CASE WHEN CTG_D = 106 THEN 19 ELSE 2 END) AS COPERACION 
from 
TG_D
where
(CTG_D=106 OR CTG_D=362)) TF
INNER JOIN TIPO_OPERACION TOP1 ON TF.COPERACION = TOP1.CTIPO_OPERACION
RETURN  
 END
