ALTER FUNCTION FN_OBTENER_OPCION_TRAFICO(@CROL INT)
RETURNS   @TABLE TABLE(COPCION_TRAFICO INT,DOPCION_TRAFICO VARCHAR(255), CROL_OPCION_TRAFICO INT,FLG_ROL_TRAFICO INT)
AS
BEGIN
INSERT INTO @TABLE
SELECT 
OPTR1.COPCION_TRAFICO, 
OPTR1.DOPCION_TRAFICO,
(SELECT RO1.CROL_OPCION_TRAFICO FROM ROL_OPCION_TRAFICO RO1 WHERE RO1.CROL=@CROL AND RO1.COPCION_TRAFICO=OPTR1.COPCION_TRAFICO )AS CROL_OPCION_TRAFICO,
(SELECT COUNT(*) FROM ROL_OPCION_TRAFICO RO WHERE RO.CROL=@CROL AND RO.COPCION_TRAFICO=OPTR1.COPCION_TRAFICO )AS FLG_ROL_OPERACION
 FROM OPCIONES_TRAFICO OPTR1 WHERE IACTIVO=1
RETURN
END