create or replace PROCEDURE spInsertarEmpleado(
EMPLOYEE_ID1 NUMBER,
FIRST_NAME1     VARCHAR2, 
LAST_NAME1      VARCHAR2, 
EMAIL1          VARCHAR2, 
PHONE_NUMBER1   VARCHAR2, 
HIRE_DATE1      DATE,         
JOB_ID1         VARCHAR2, 
SALARY1         NUMBER, 
COMMISSION_PCT1 NUMBER,  
MANAGER_ID1              NUMBER,    
DEPARTMENT_ID1           NUMBER )
IS
--declare 
--EMPLOYEE_ID1 int;
--begin
--    SELECT nvl( max(employee_id),0)+1 into EMPLOYEE_ID1 from employees where 1=1;
--end;
BEGIN
    insert into employees(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID)
    values(EMPLOYEE_ID1,FIRST_NAME1,LAST_NAME1,EMAIL1,PHONE_NUMBER1,HIRE_DATE1,JOB_ID1,SALARY1,COMMISSION_PCT1,MANAGER_ID1,DEPARTMENT_ID1);
END spInsertarEmpleado;